rpm: avoid build failure from missing build-id in xen-syms
RPM build error:
    Processing files: xen-hypervisor-4.6.6-38.fc28.x86_64
    error: Missing build-id in
    /home/user/rpmbuild/BUILDROOT/xen-4.6.6-38.fc28.x86_64/usr/lib/debug/xen-syms-4.6.6
    error: Generating build-id links failed